<!-- Page Content -->
  <div id="bg">
  <div class="container">

      <!-- Page Heading/Breadcrumbs -->
      <div class="row">
          <div class="col-lg-12">
              <h1 class="page-header">Sign Up
                  <small></small>
              </h1>
              <ol class="breadcrumb">
                  <li><a href="/">Home</a>
                  </li>
                  <li class="active">Sign Up</li>
              </ol>
          </div>
      </div>
      <!-- /.row -->

      <!-- Content Row -->
      <div class="row">
          <div class="form">
                <form action="action_page.php">
                  <label for="fname">First Name</label>
                  <input type="text" id="fname" name="firstname">

                  <label for="lname">Last Name</label>
                  <input type="text" id="lname" name="lastname">
                  <label for="fname">First Name</label>
                  <input type="text" id="fname" name="firstname">

                  <label for="lname">Last Name</label>
                  <input type="text" id="lname" name="lastname">
                  <label for="fname">First Name</label>
                  <input type="text" id="fname" name="firstname">

                  <label for="lname">Last Name</label>
                  <input type="text" id="lname" name="lastname">

                  <label for="country">State</label>
                  <select id="country" name="country">
                    <option value="australia">Australia</option>
                    <option value="canada">Canada</option>
                    <option value="usa">USA</option>
                  </select>

                  <input type="submit" value="Submit">
                </form>
          </div>
      </div>
      <!-- /.row -->

      <hr>
